openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: Initial example to submit Elasticsearch queries

paths:
  /search:
    get:
      summary: 'Submits a query to Elasticsearch'
      operationId: search
      tags:
        - search
      parameters:
        - name: query
          in: query
          description: Query to be submitted
          schema:
            type: string
        - name: page
          in: query
          description: Interval to get query data
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    SuggestionPair:
      type: object
      properties:
        original:
          type: string
        suggestion:
          type: string

    Result:
      type: object
      properties:
        Hits:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              url:
                type: string
              abs:
                type: string
        suggest:
          type: array
          items:
            $ref: '#/components/schemas/SuggestionPair'
        autocomplete:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              url:
                type: string
        total:
          type: integer


    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string